### ISSUE TITLE
Release Cycles

### ISSUE THREAD

**Issue by jaredallard** [TARDIX/Chameleon#14]
It'd be awesome if we had release cycles and could mark issues with milestones for each release cycle. Yes, this is rolling release, but it'd be awesome if we had some sort of internal versioning.

**Comment by DemHydraz** [comment]
I have no objections.

**Comment by jaredallard** [comment]
Shall I suggest we discuss this Wednesday @ 2:00PM PST ?

**Comment by DemHydraz** [comment]
UTC please.

**Comment by jaredallard** [comment]
21:00 UTC

**Comment by DemHydraz** [comment]
ok.
